### ISSUE TITLE
Accepting Pull Request

### ISSUE THREAD

**Issue by theogf** [jacobcvt12/GradDescent.jl#4]
Hello,

I could not find your mail, so maybe this issue, will notify you. I made a pull request where I updated your package for Julia 1.0, and made some small modification (added Vanilla GradDescent and exported abstract type). Could you accept the pull and eventually add me as a collaborator so I can maintain  the package?

Cheers,

Theo

**Comment by jacobcvt12** [comment]
Thanks for bumping this @theogf . So sorry I took so long to review the PR! Appreciate the changes that you made. Sure - I can use some help maintaining the package. I'll add you as a collaborator.
