### ISSUE TITLE
Make new release and link with Attobot 

### ISSUE THREAD

**Issue by theogf** [jacobcvt12/GradDescent.jl#6]
It would be good to release the new version and to automatize the release process with the new standard tool for package release : https://github.com/attobot/attobot

**Comment by theogf** [comment]
Bump :)

**Comment by jacobcvt12** [comment]
Thanks for the reminder! I integrated attobot and published a release but got an error (issue #7 ) about there being no REQUIRE file. I thought the REQUIREs were dropped for Pkg3. Any ideas?

**Comment by theogf** [comment]
Oh right I made this mistake as well.
You still need to keep the REQUIRE file (for backward compatibility I suppose) while not putting the stdlibs, it should be : 
```
julia 0.7
Distributions
ForwardDiff
```
I think

**Comment by jacobcvt12** [comment]
Attobot is integrated and working! All changes have been merged into metadata
